- name: Redeploy homelab stack
  listen: Redeploy homelab stack
  community.docker.docker_stack:
    state: present
    name: "{{ stack_name }}"
    compose: >-
      {{


        [ homelab_root + '/hl-traefik.yaml' ] +
        lookup('ansible.builtin.fileglob', services_dir + '/*.yaml', wantlist=True)
      }}
