- name: Validate required vars
  ansible.builtin.assert:
    that:
      - name is defined
      - image is defined
      - port is defined
      - host is defined
      - path is defined
- name: Docker registry login
  community.docker.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
  when: registry_url is defined and registry_username is defined and registry_password is defined
- name: Render service (Swarm)
  ansible.builtin.template:
    src: service-swarm.yaml.j2
    dest: "{{ services_dir }}/{{ name }}.yaml"
    mode: "0644"
  notify: Redeploy homelab stack
- name: Render router (Traefik File Provider)
  ansible.builtin.template:
    src: route-file.yaml.j2
    dest: "{{ homelab_root }}/dynamic/routers/{{ name }}.yaml"
    mode: "0644"
  notify: Redeploy homelab stack
- name: Force handler execution
  ansible.builtin.meta: flush_handlers
