- hosts: homelab
  become: true
  vars:
    homelab_root: /opt/homelab
    stack_name: hl
    services_dir: "{{ homelab_root }}/services"
    dynamic_dir: "{{ homelab_root }}/dynamic/routers"
  roles:
    - role: _shared
    - role: service
      vars:
        # wajib dikirim via -e saat run:
        # name, image, port, host, path
        replicas: 1
        priority: 2000
        playbook_action: add
  post_tasks:
    - name: Get service files
      find:
        paths: "{{ services_dir }}"
        patterns: "*.yaml"
      register: service_files
    - name: Deploy service to homelab stack (with registry auth)
      shell: |
        docker stack deploy \
          --with-registry-auth \
          --compose-file "{{ item }}" \
          "{{ stack_name }}"
      loop: "{{ service_files.files | map(attribute='path') | list }}"
      when: service_files.files | length > 0
    - name: No services to deploy
      debug:
        msg: "No service files found in {{ services_dir }}"
      when: service_files.files | length == 0
