- name: Add a new service
  hosts: homelab
  become: true
  vars:
    homelab_root: /opt/homelab
    stack_name: hl
    services_dir: "{{ homelab_root }}/services"
    dynamic_dir: "{{ homelab_root }}/dynamic/routers"
  roles:
    - role: shared
    - role: service
      vars:
        # wajib dikirim via -e saat run:
        # name, image, port, host, path
        replicas: 1
        priority: 2000
        playbook_action: add
  post_tasks:
    - name: Deploy new service only (keep others intact)
      community.docker.docker_stack:
        state: present
        name: "{{ stack_name }}"
        with_registry_auth: true
        prune: false
        compose: >-
          {{ [ homelab_root + '/hl-traefik.yaml', services_dir + '/' + name + '.yaml' ] }}
