- name: Homelab bootstrap
  hosts: homelab
  become: true
  vars:
    homelab_root: /opt/homelab
    stack_name: hl
    services_dir: "{{ homelab_root }}/services"
    dynamic_dir: "{{ homelab_root }}/dynamic/routers"
    traefik_logs_dir: /var/log/traefik
  pre_tasks:
    - name: Validate required variables
      ansible.builtin.fail:
        msg: "main_domain is required. Please set it with -e 'main_domain=yourdomain.com'"
      when: main_domain is not defined or main_domain == ""
    - name: Check if traefik stack already exists
      ansible.builtin.shell:
        cmd: set -o pipefail && docker stack ls --format "table {{ '{{.Name}}' }}" | grep -w "{{ stack_name }}"
        executable: /bin/bash
      register: stack_exists
      failed_when: false
      changed_when: false
    - name: Check if traefik service is running
      ansible.builtin.shell:
        cmd: set -o pipefail && docker service ls --format "table {{ '{{.Name}}' }}" | grep -w "{{ stack_name }}_traefik"
        executable: /bin/bash
      register: traefik_exists
      failed_when: false
      changed_when: false
    - name: Skip initialization if traefik already running
      ansible.builtin.debug:
        msg: "Traefik stack '{{ stack_name }}' already exists. Skipping initialization. Use update-service.yaml for updates."
      when: stack_exists.rc == 0 or traefik_exists.rc == 0
    - name: Stop playbook if traefik exists
      ansible.builtin.meta: end_play
      when: stack_exists.rc == 0 or traefik_exists.rc == 0
  roles:
    - role: common
    - role: _shared
    - role: traefik
