- name: Update a service
  hosts: homelab
  become: true
  vars:
    homelab_root: /opt/homelab
    stack_name: hl
    services_dir: "{{ homelab_root }}/services"
    dynamic_dir: "{{ homelab_root }}/dynamic/routers"
  pre_tasks:
    - name: Check if stack exists
      ansible.builtin.shell:
        cmd: set -o pipefail && docker stack ls --format "table {{ '{{.Name}}' }}" | grep -w "{{ stack_name }}"
        executable: /bin/bash
      register: stack_exists
      failed_when: false
      changed_when: false
    - name: Fail if stack doesn't exist
      ansible.builtin.fail:
        msg: "Stack '{{ stack_name }}' doesn't exist. Run site.yaml first to bootstrap the homelab."
      when: stack_exists.rc != 0
  roles:
    - role: shared
    - role: service
      vars:
        # wajib dikirim via -e saat run:
        # name, image, port, host, path
        replicas: 1
        priority: 2000
        playbook_action: update
  post_tasks:
    - name: Update only the targeted service (no full redeploy)
      community.docker.docker_stack:
        state: present
        name: "{{ stack_name }}"
        with_registry_auth: true
        prune: false
        compose: >-
          {{ [ homelab_root + '/hl-traefik.yaml', services_dir + '/' + name + '.yaml' ] }}
